### PR TITLE
Adding a GUI to the bot.

### PR DESCRIPTION
**Pull request by Tehmo3**
Hey, 

I sent you a reddit message but I thought you would see it better here. I have coded a small GUI to go along with your bot, I'm new to the whole programming thing but hopefully this is up to your standards and could be added... includes a slightly updated readme.md. 

Let me know what you think :)
Thanks
TehMo3

### CODE REVIEW

**Comment by dosaki** [comment]
I think you left your account JSON under accounts

**Comment by MRokas** [comment]
Dude, .json has your PTC login details.

**Comment by dosaki** [comment]
And change your password ASAP

**Comment by Tehmo3** [comment]
Rookie mistake :hushed: 

I think its fixed now

**Comment by MRokas** [comment]
It still can be viewed. You should go change it.

**Comment by Tehmo3** [comment]
Where are all the places it can be seen? Not sure where they all are

**Comment by dosaki** [comment]
One can see it in the commit history.
The fix is to change your password everywhere you use it. Even if the account name is different.

**Comment by MRokas** [comment]
https://github.com/TomTheBotter/Pokemon-Go-Bot-Working-Hack-API/pull/56/commits/8735cfcd9f02a08ec93f91c1991cb1eb8f9d8ab5

Also, you should read up about commiting. This commit has bunch of unnecessary stuff. Or use IDE/Code-Editor which makes it easy to add items to commit.

**Comment by Tehmo3** [comment]
Ok everythings getting changed. 
Thanks for all your help, I'll read up too, seems like I fucked up bad :frowning:

**Comment by dosaki** [comment]
It happens sometimes, but seriously, change your passwords now.

**Comment by Tehmo3** [comment]
Think I got all of them. Jeez that was a bad mistake to make

**Comment by dosaki** [comment]
Monitor your emails and set up 2-factor authentication (if you haven't yet!).

Hope nothing bad happens to you :)

**Comment by dosaki** [comment]
More on-topic: by GUI do you meant a startup config?

**Comment by Tehmo3** [comment]
Yea its a new file that either runs a small dialogue box (?) so you can enter your info and it generates the config.json file for you or it just starts the bot as usual.

**Comment by MRokas** [comment]
Would you be able to add data displayer using data from accounts/*.json ?

**Comment by Tehmo3** [comment]
Umm potentially? Do you mean like an interface that displays pokemon caught and whats in your inventory etc?

**Comment by MRokas** [comment]
Yes. It's just little annoying. Player stats are in inventory.
`data.GET_INVENTORY.inventory_delta.inventory_items[13].player_stats` for me is exp and etc

**Comment by Tehmo3** [comment]
Hmm I see, honestly that seems like its already getting out of my depth but I will certainly give it a shot when I get some time!

**Comment by Jay1** [comment]
if you're still at it, you may want to [check this out](https://github.com/Novalys/PokemonGo-Bot-SimpleGUI)...  it could be useful for you

**Pull request closed without merging**
