### PR TITLE
Add ability to release duplicate pokemon if desired

### PR DESCRIPTION
**Pull request by beeedy**
Config now contains an option to release duplicate pokemon, keeping the one with the highest CP. Also added the ability to only release pokemon that are below xx% CP of the top CP pokemon

### CODE REVIEW

**Comment by beeedy** [comment]
For clarity, this is disabled by default. 
Also, DUPLICATE_CP_FOREGIVENESS is a scaler value that is multiplied to the strongest pokemon's CP before deciding if the pokemon with the lesser CP should be released.

**Comment by jolbol1** [comment]
screen shot 2016-07-25 at 02 57 32 Had 250 pokemon, worked like a charm! Thanks man!

**Comment by ruffnecktsk** [comment]
I think that is needed to add check also KEEP_CP_OVER variable, because i've launched with RELEASE_DUPLICATE = true, and what i see?

2016-07-25 12:02:53,677 [    pgoapi] [ INFO] Releasing pokemon: Vaporeon IV: 84.4444444444
2016-07-25 12:02:53,677 [    pgoapi] [ INFO] Releasing pokemon: Vaporeon IV: 77.7777777778
2016-07-25 12:02:53,677 [    pgoapi] [ INFO] Releasing pokemon: Flareon IV: 75.5555555556

all of them was with over 1500cp :(

**Comment by beeedy** [comment]
While i am not entirely sure what else you expected to happen, I am sorry you lost those 3. It looks like this has already been mended and you can not pick a max CP it will release

**Comment by charredchar** [comment]
@beeedy You would think it would adhere to the rules, 

`"MIN_KEEP_IV" : 70,
"KEEP_CP_OVER": 1000,`

before just releasing any duplicates. I personally have been getting duplicates that don't even meet these requirements so I was happy for the RELEASE_DUPLICATE but I am now afraid to touch it.

**Comment by beeedy** [comment]
It makes no sense for it to adhere to the rules, because otherwise any duplicates it throws out would have been thrown out anyway for not meeting those rules. 

Also, I highly suggest against using this bot. This was a bot that duplicated and took credit for another teams project. I suggest switching to the original bot: https://github.com/j-e-k/pgoapi/issues/

**Pull request merged**
