### PR TITLE
add MIN_KEEP_IV_CP option to config and BAD_FORTS option to location.py

### PR DESCRIPTION
**Pull request by mudzereli**
`MIN_KEEP_IV_CP` prevents bot from keeping things like 14 cp Eevee's that are 90% IV
`BAD_FORTS` allows bot to avoid forts which it gets stuck walking to (user defines in location.py). this allowed me to run the bot overnight without getting stuck once I entered the 3-4 bad forts in my area.

### CODE REVIEW

**Comment by beeedy** [comment]
The name given to this parameter is slightly misleading in my opinion. It appears to just be a limit on CP and nothing to actually do with IV. Might be better to rename to something such as MIN_KEEP_CP

**Comment by mudzereli** [comment]
I get what you're saying but there's already `KEEP_OVER_CP` which keeps all pokemon over a certain CP even if they don't pass the IV checks and this `MIN_KEEP_IV_CP` adds an additional requirement to the IV check that only keeps pokemon above a certain CP. As of now, the bot will keep a bunch of very-low CP pokemon (as long as they are high IV - i.e. 50 CP pokemon), but this allows you to

**Comment by beeedy** [comment]
hmm I see what you are saying. Would there ever be a reason to keep a pokemon over a certain CP that doesn't also meat the IV check? Maybe it would just be best to combine these two checks with the option to treat them as an AND or an OR check. Completely spit-ballin' here

**Comment by mudzereli** [comment]
> Would there ever be a reason to keep a pokemon over a certain CP that doesn't also meat the IV check?
Yes because many players will have (or want to level) some not-so-great-but-already-leveled pokemon (my 1700 Vaporeon is 70% IV) and as they find higher-IV and better pokemon, they are more likely to tighten their pokemon catching settings. (for me, it's better to look at this `KEEP_OVER_CP` like a safety net - i.e. never discard anything above this)

With the updated code and separate IV check, instead of saying "Keep all pokemon over 1000 CP and all High-IV(>80%) pokemon" you can say "Keep all pokemon over 1000 CP and all High-IV(>80%) pokemon over 500 CP"

**Comment by squej1** [comment]
i for some reason keeps getting code error no fort to walk to any help fixing this

**Comment by lawonga** [comment]
I also am getting the 'no fort to walk to'

**Comment by MisterFab1an** [comment]
Second this, no forts

**Comment by beeedy** [comment]
For those unaware, this project is a copy of another project with the licensing and credit removed. I recommend heading over to the original project where most of these problems have been solved: github.com/j-e-k/pgoapi

**Pull request closed without merging**
