### PR TITLE
Auto evolve basic pokemon

### PR DESCRIPTION
**Pull request by Bramzor**
Patch to allow all basic pokemon specified to evolve the one with the highest CP
Requested in issue: #116

### CODE REVIEW

**Comment by beeedy** [comment]
It looks like this is only evolves pidgey and rattata, if we go down the route of adding auto-evolving it might be better to just add all pokemon.  A table could be structured that included information pertaining to if a pokemon evolves, which pokemon candy it needs, and how much of said candy it needs. 

One problem however is when you hit a pokemon that evolves more than once you will never hit the last evolution as the bot will burn up candy continuously on the first evolution. A system could be setup to check if a second stage evolution is already owned, and if so, only evolve to last stage. This way the bot would auto evolve a pokemon from the first stage to the last stage before starting over. Completely spit balling here, and could see this needing a lot more parameters for customization, but may be better to add more than just rattata

**Comment by Bramzor** [comment]
The reason you only want to evolve pidgeys and rattatas and other common pokemon is to receive the evolve bonus of 500xp every time. This is a way to quickly level a character.
You don't want to do this with every single pokemon as it is better to evolve more rare pokemon at a higher level because they will start with a higher CP.

So it is made for exactly that, leveling pidgeys, weedles etc.

**Comment by beeedy** [comment]
I completely understand where you are coming from, but I think the subset of pokemon that each person consider 'rare' and worth evolving for XP is highly subjective. Personally, I would prefer to evolve all my pokemon automatically with 'transfer duplicates' enabled. Understandably this isn't everyone's stance, but it would be nice if each user had the ability to pick which pokemon were auto-evolved

**Comment by TomTheBotter** [comment]
I'm not sure which pokemon to evolve; like what should it have a higher cp or iv?

**Comment by beeedy** [comment]
I am sorry, I no longer have input on this project. All my efforts will go towards the original: https://github.com/j-e-k/pgoapi

**Comment by zwhitchcox** [comment]
What happened? Why are there no more accepted pull requests any more?

**Pull request closed without merging**
